- name: Деплой Docker-образов с помощью Ansible
  hosts: all
  gather_facts: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: docker_install
      include_role:
        name: docker_install

    - name: redmine_install
      when: "'webservers' in group_names"
      include_role:
        name: redmine_install  

    - name: nginx_install
      when: "'load_balancer' in group_names"
      include_role:
        name: nginx_install
    

    - name: start datadog
      import_role:
        name: datadog.datadog
      become: yes
      when: "'webservers' in group_names"