- name: Include vars from role
  include_vars:
    dir: vars

- name: Create nginx config directory
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: '0755'
  become: true

- name: Copy nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /opt/redmine/.env
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  become: true

- name: Pull and run nginx
  docker_container:
    name: nginx-lb
    image: nginx:latest
    state: started
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro